version: 2
run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - govet
    - gocyclo
    - staticcheck
    - ineffassign
    - revive
    - errcheck
    - unused
    - gocritic
    - durationcheck

issues:
  exclude-dirs:
    - .history
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
