run:
  timeout: 5m
  issues-exit-code: 1
linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - staticcheck
    - ineffassign
    - revive
    - errcheck
    - unused
    - typecheck
    - gosimple
    - stylecheck
    - gocritic
    - durationcheck
issues:
  exclude-dirs:
    - .history
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
